# Misc params
data_dir: data
output_dir: output


# Basic training parameters
device: cpu    # cpu, cuda
random_seed: 123  # Seed for torch.manual_seed() and np.random.seed()
epochs: 50
batch_size: 32 # 256

# Optimizer params
# Supported optimizers: sgd, sgd_momentum, adagrad, adam, entropy_per_layer, entropy_per_neuron
optimizer: entropy_per_layer
learning_rate: 0.1
ent_beta: 1  # Param for entropy optimizers (for learning rule update)
momentum: 0.1   # Used in sgd_momentum
# Note: Define other optimizers, optimizer params as needed and add them to code in model_utility.create_optimizer()

# Network architecture
ann_input_nodes: 784
output_nodes: 10
#ann_layer_units: [64, 32, 16]
#ann_layer_units: [128, 64]
ann_layer_units: [50, 50]
ann_layer_activations: ['relu', 'relu', 'relu']
#ann_layer_dropout_rates: [0.2, 0.2, 0.2]
ann_layer_dropout_rates: [0.0, 0.0, 0.0]